### ISSUE TITLE
Move route info into review model

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#103]
Currently, human-readably route info is injected at runtime in BaseProposalsView.add_route_info() . This approach makes the information hard to access outside of the Proposal views. This routine should be moved to a more useful location, for example the Review model.

To replace the code in the Proposal views, queryset annotations which then retrieve the route info from the review model seem like a good option.

**Comment by tymees** [comment]
I'm hijacking this issue as I need this method somewhere
