### ISSUE TITLE
Request 'track changes' is on on revision documents

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#104]
The committees prefer researchers to enable 'Track changes' in their Word documents when modifying them for a revision.

We need to add a text asking the researcher to do so. Desiree proposed the following:
> Bij revisie: gebruik Track Changes of dien ook (Extra documenten) een vergelijkingsbestand in.

I think this is a bit short, so I'd like to propose:
> Indien je een document moet wijzigen voor een revisie vragen wij je om 'Track changes' aan te zetten, of een apart bestand bij te voegen met de wijzigingen onder 'Extra documenten'.

**Comment by miggol** [comment]
Fixed in #117
