### ISSUE TITLE
Removing non-responsive reviewers may leave review in hung state

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#106]
I believe this is because Review.update_go() is called when a review is created, but not when assignees are changed at a later date. The latter can leave the review forever waiting for the next decision to be taken.

(though I may be wrong)

**Comment by tymees** [comment]
You are both correct and wrong. ``Review.update_go`` is only called when a decision is _changed_. 

But yes, adding this call to ``ReviewAssignView``'s ``form_valid`` could be the solution. (Which would be a nice easy fix).
Does require some testing to be sure.

**Comment by tymees** [comment]
Alternatively, hooking into Django's ``delete object`` signal might work

**Comment by tymees** [comment]
Fixed in #119
