### ISSUE TITLE
High task count hangs server

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#125]
It is currently possible to enter a very high amount of tasks or sessions in the study form. Doing so hangs the server until it can process this ridiculous SQL request.

Might be better in production with an actual SQL server than with SQLite, but still a nasty bug.

**Comment by tymees** [comment]
Do you have the debug toolbar enabled?

That has a tendency of adding 300% overhead on SQL queries, on top of the innefficencies of SQLite. 

That being said, optimizing the querysets isn't a bad idea. Often you can reduce the time it takes by simply instructing Django to prefetch data in the initial query. (Normally it's queried when needed, but that increases the amount of queries exponantially).

**Comment by miggol** [comment]
Good to know! I don't really know how I would optimize the querysets. My plan was to just limit the amount of tasks that can be added to a proposal. Something reasonable like 20 million. (I kid, but there's actually no limit now)

**Comment by tymees** [comment]
Or we could just trust our researchers to not go overboard and subject the participants to ~~torture~~ insanely complicated tasks

**Comment by miggol** [comment]
Fixed in develop

**Comment by miggol** [comment]
Fixed in develop
