### ISSUE TITLE
Archive should show date accepted

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#127]
It currently lists the date of the last edit. Per Desiree:

Ik zie nu dat er in het archief niet de datum van goedkeuring staat, maar alleen ‘last edited’. Dat is niet altijd precies de datum van goedkeuring; dat goedkeuren gaat via de mail, en daarna moet ik het in de portal nog goed zetten, dat is niet altijd dezelfde datum. Die goedkeuringsdatum staat wel ergens in de portal, want dat geef ik aan, maar ik zie ‘m niet in het archief.

Mag dit op het lijstje? Ik gebruik de info uit het archief om de goedgekeurde studies op de website te zetten; dan is het fijn als de goedkeuringsdatum overeenkomt met de werkelijke goedkeuringsdatum.

**Comment by tymees** [comment]
The annoying part of this, is that the archive view uses the same template as the other proposal list views.

So we either have to duplicate the template (as last editted is preferable on the other pages), add a context var which switches the dates or add it seperatly

**Comment by miggol** [comment]
Fixed in #142
