### ISSUE TITLE
HTML is escaped in form.as_table descriptions

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#146]
Thought this would be a quick fix but I'm kind of stuck, so I'm paging @tymees for this one. An example can be seen `ProposalUpdate`:

> Zijn er nog andere onderzoekers bij deze studie betrokken die \<strong>niet\</strong> geaffilieerd zijn aan een van de onderzoeksinstituten van de Faculteit Geestwetenschappen van de UU? :

The text itself is defined in the model, where `Django.utils.safestring.mark_safe()` has no effect on it, either inside or outside of the translation hook. Using the safe filter in the template also has no effect, meaning this string is explicitly escaped somewhere inbetween. Any ideas?

Update: tried `mark_safe_lazy()` as well to no avail

**Comment by tymees** [comment]
These things can be very annoying to fix....

From what I recall, when using Forms the mark_safe in models when also using gettext_lazy (which we need to use there) simply doesn't work. 

What does work, is using mark_safe in the form's ``__init__``. For example: https://github.com/UiL-OTS-labs/ethics/blob/2f7e6c45238219487fe916bc756bb68555192ebe/proposals/forms.py#L545

It's ugly AF, but at least it works.

**Comment by miggol** [comment]
It appears the above method no longer works in combination with SoftValidationMixin. Because the escaped HTML is rather jarring and needs fixing, I've now hard-coded form labels with HTML in the Meta class (which still works) but which is arguably even more ugly. This method was already selectively applied elsewhere. I added comments in the relevant model fields for reference.
