### ISSUE TITLE
Supervisor decisions are mailed to FETC instead of applicant

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#149]
> dat de email naar de fetc gestuurd wordt ipv naar de student/promovendus? Volgens mij kreeg ik dit soort mailtjes nooit. Ik kan deze hele aanvraag nergens vinden overigens.

**Comment by miggol** [comment]
In Develop, all applicants now receive an email with comments on negative supervisor response. They already did get an email if it was accepted through `start_assignment_phase`. I've contacted the Desiree about if she still wants to receive them as well.

**Comment by miggol** [comment]
Fixed in #160
