### ISSUE TITLE
Bug: preassessment pdf seems to use wrong template

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#234]
To reproduce:

1. Submit a preassessment proposal
2. View the pre generated pdf from the links provided to submitter and supervisor
3. Notice the trajectories header is still there

`proposals:pdf` with the right PK does use the right template though

**Comment by tymees** [comment]
Might it be an idea to just axe the on-disk versions of the PDF in favour of the on-the-fly generated PDF?

It's kinda redundant

**Comment by miggol** [comment]
Fixed in #247
