### ISSUE TITLE
Add jsPsych to registrations model

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#301]
I thought we had already done this at some point, but I don't see it come up in the mails from the EDDA course.

**Comment by tymees** [comment]
Ehm how would this need to be added tho?

As the current registration kinds seem to encompass jsPsych already, even if it's not directly mentioned

**Comment by tymees** [comment]
Or was there a request I missed to add a explicit option for it?

**Comment by miggol** [comment]
Yeah, there was a specific request by Iris (?) at some point and it must have slipped by me.

**Comment by tymees** [comment]
I don't think Iris has the authority to request this without Desiree also chiming in....
