### ISSUE TITLE
Compare proposal not working correctly with mismatching number of studies

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#317]
The compare proposal page doesn't work correctly (if at all) if the number of studies between versions differ.

The offending line seems to be:
``{% for study, p_study in proposal.study_set.all|zip:p_proposal.study_set.all %}``

This works great if the two iterables are of comparable length, but ``zip()`` stops if the shortest iterable is exhousted. This issue is also present a bit further down the page in the ``session`` comparision section.

One solution could be:
1. Use a different method to combine the two lists. I would suggest a zip method which fills in 'None' for when the shortest list is out of items
2. Change the template such that it can handle missing study/session objects. Right now it expects it to be there

Another might be to completely rewrite the template such that the page is split in two, with both sides displaying a full readout of a proposal. Thus, instead of zipping 2 proposals together, write one template to display 1 proposal and call it twice for both the current and old proposal. Then, use some JS to compare the two against eachother.
One problem with this solution might be aligning the different parts such that they are next to eachother in the page. (Otherwise you might get a study next to a documentlist).

The first option is way easier, but the second one might be better long term. I think it might be a good idea to create one template to display an entire proposal, such that we can reuse that. For example, the PDF template might also make use of that template (as that template really needs a visual overhaul). Another more uncertain usecase might be as general review page, as the proc.reg. wants a review page like that (and doing it this way means we could steal their comment code). 

In anycase, I think it might be a good idea to split the current diff template up into separate parts, as it's very long and a minefield of nested if's and for's.

**Comment by miggol** [comment]
Solution 1 is the fix we need right now, and could implement with minimum effort. 

> Another might be to completely rewrite the template such that the page is split in two, with both sides displaying a full readout of a proposal. Thus, instead of zipping 2 proposals together, write one template to display 1 proposal and call it twice for both the current and old proposal. Then, use some JS to compare the two against eachother.

Could the JS to compare them to one another be adapted from the compare documents page? I don't know how well it would handle html formatting, but we could at least apply it to the textual answers.

> I think it might be a good idea to create one template to display an entire proposal, such that we can reuse that. For example, the PDF template might also make use of that template (as that template really needs a visual overhaul). Another more uncertain usecase might be as general review page, as the proc.reg. wants a review page like that (and doing it this way means we could steal their comment code).

I think this is a very good idea. My idea for the uil.questions package was to create forms with enough smarts to display themselves and their answer, for now with the `{% display_question $question }` tag. This would be used in the review and overview pages, and could possibly be adapted to diffing.

> In anycase, I think it might be a good idea to split the current diff template up into separate parts, as it's very long and a minefield of nested if's and for's.

That would be a good start. Do we ever get ordering complaints when studies / sessions don't match? We could for example have a compare_study page, where you could choose which other study from the parent you want to compare it to. But considering the ordering of studies is quite rigid I don't expect us to really need that.

Finally, I want to have said that I don't like the current diffing feature in general. This goes double for implementing it again in procreg. I think the benefits don't outweigh the development and maintenance costs compared to a "mark changed questions" side by side view. I feel like by implementing diffing to any extent we're kind of promising that it will work *well*, which for me is a big promise.

**Comment by tymees** [comment]
> Could the JS to compare them to one another be adapted from the compare documents page? I don't know how well it would handle html formatting, but we could at least apply it to the textual answers.

Those pages already use the same comparison code. It handles HTML fine for the most part (it's actually a JS library I modified a bit).

> I think this is a very good idea. My idea for the uil.questions package was to create forms with enough smarts to display themselves and their answer, for now with the {% display_question $question } tag. This would be used in the review and overview pages, and could possibly be adapted to diffing.

Sounds like an awesome feature; while I still have no clear picture on the implementation, I think it won't need much adapting as the JS library just compares the contents of two divs. I think that just calling a template tag twice would not be hard ;)

> That would be a good start. Do we ever get ordering complaints when studies / sessions don't match? We could for example have a compare_study page, where you could choose which other study from the parent you want to compare it to. But considering the ordering of studies is quite rigid I don't expect us to really need that.

Well, this issue is a mismatch error in a sense. But I don't think I've ever seen a issue reported about studies using a different order between versions. (Well, at least since we fixed the issue of them never being in the right order)

> Finally, I want to have said that I don't like the current diffing feature in general. This goes double for implementing it again in procreg. I think the benefits don't outweigh the development and maintenance costs compared to a "mark changed questions" side by side view. I feel like by implementing diffing to any extent we're kind of promising that it will work well, which for me is a big promise.

I don't think diffing is really on the table for procreg at the moment, unless I'm mistaken? If it is, I think we can 1) shoot it down for the MVP and 2) design something that is a little bit less horrible. (For example, we could just add a log of changes ;) )

That being said, I do agree with you that it might be overpromosing with a risk of underdelivering; I've never liked it either. However, it was already in there since I took the project over, and suggesting removing it is would be a challange. But to it's credit, ever since we did the full diffing upgrade last year it's been a lot better.
