### ISSUE TITLE
New reference number format

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#89]
The FETC wants to remove the Solis-ID from the reference numbers. 

Currently, reference numbers are generated by the ``generate_ref_number`` and ``generate_revision_ref_number`` functions (in ``proposals/utils/proposal_utils.py``) for new and revision proposals respectively. 

The example format given by the FETC is ``year-number-revision`` where year is the last two digits of the year, number is a counter of all proposals in that year and revision the revision number of the specific proposal.

This should be easy to implement. The year we already have and the number can be implemented by a simple count query.
The revision number itself isn't that hard to implement, but we have to think about backwards compatibility sadly. I've asked the FETC if all old proposals should get a new number.

In the likely scenario that they won't get a new number, we have to write some code to detect old, old-old or new reference numbers. A quick way to implement this is to add a new field to the Proposal indicating the version of the reference number. 

(Some background, the 'old-old' format uses a 'username-number-year' format, while the 'old' format adds a revision to the format:  'username-number-revision-year')

That way we can do a simple check for the version, and use the appropiate version of ``generate_revision_ref_number`` function.

A different approach would be to do some string analysis, like we do now for differentiating between 'old-old' and 'old'. However, the current check would actually classify the new format as the 'old-old' format, as it only checks the number of parts.

**Comment by tymees** [comment]
A proposal for the new ``generate_ref_number``:

```python

def generate_ref_number():
    """
    Generates a reference number for a new(!) Proposal.
    NOTE: Use generate_revision_ref_number to create reference numbers for
    revisions! This function will always create a new ref.num. with version = 1
    :return: a reference number in the format {nr}-{vr}-{current_year}, 
    where nr is the number of Proposals created  in the current year excluding 
    revisions. Vr is the version of this proposal, this function will always return vr = 1.
    """
    from ..models import Proposal

    # Set default values
    current_year = datetime.now().year
    proposal_number = 1
    version_number = 1

    try:
        # We count all proposals for this year by selecting all proposals
        # with a reference number ending with the current year.
        num_proposals = Proposal.objects.filter(
            reference_number__endswith=current_year,
        ).count()
        proposal_number = num_proposals + 1
    except Proposal.DoesNotExist:
        # Should not happen(TM)
        pass

    return '{:02}-{:02}-{}'.format(
        proposal_number,
        version_number,
        current_year
    )
```

I've used a slightly different format than in my initial post: 'nr-vr-year'. This way the function doesn't have to be aware of the older formats to work, as they all have the year at the end.

**Comment by tymees** [comment]
Ended up with a slightly different implementation, it was easier to just check the `created_on` variable in the count query. 

My implementation is in PR #90 

There is a small bug however:
If you have Proposal A with an old ref-num and make a revision B with A as parent, everything is fine. (20-001-02)
If you then make a revision C with B as parent, everything is still fine. (20-001-03)
If you then make revision D with A as parent again, you will be given the ref number 20-002-02. 

It's actually very hard to solve this, as the function that generates a new ref number from old ref numbers cannot be aware of any revisions with the new ref.num. (There is simply no easy way of finding those without the new proposal number used by the other revisions). 

To be honest, I don't think it's a big problem. At least not big enough to justify the effort of fixing it

**Comment by JeltevanBoheemen** [comment]
Regarding the bug: I agree that it's minor enough to not warrant a complex fix.
