### ISSUE TITLE
Allow all committee members to see currently open proposals

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#93]
The best way to do this (I think) would be to clone `AllProposalReviewsView`, and change that view such that:

1. It is viewable on the basis of committee-group membership instead of secretary membership
2. It selects all Review objects that are open

The template used in that view should already restrict actions, such that only the secretary can do things. 

I would recommend checking if the same thing holds true for the details page!

**Comment by miggol** [comment]
Implemented in #102
