### ISSUE TITLE
Add the review-route to the supervisor list

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#94]
It has been requested that supervisors can view which track (short or long track) a proposal is assigned to.

To get this info, you can look at proposal.review_set. This is a QuerySet, so you'll need to use the QuerySet API to get info from that attribute.

Note: a proposal might have 2 reviews. One for the supervisor and one for the committee. Using the ``.last()`` should pick the latest one ;)

The way column names are added is a bit... interesting, so if you need help, you know where to find me!

**Comment by tymees** [comment]
Bonus points for figuring out how to add this column to the 'details' part of the table. I don't think this functionality is enabled right now, so that needs to be done first.

(Googling DataTables will get you the documentation for the library that makes those fancy tables).

Feel free to leave that to me tho.

**Comment by miggol** [comment]
Implemented in merge #101
